### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by chenhao-1115** [xinliy/python_depth_to_point_cloud#1]
请问参数focal_length=50, scalingfactor=1000代表什么？

**Comment by xinliy** [comment]
You can look up this very detailed explanation on this website: http://ksimek.github.io/2013/08/13/intrinsic/. Basically focal length is a static parameter in a pinhole camera and scaling factor won't affect the shape of the output point cloud.

**Comment by Cli98** [comment]
> 请问参数focal_length=50, scalingfactor=1000代表什么？

https://stackoverflow.com/questions/49598937/how-to-convert-the-depth-map-to-3d-point-clouds
